#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# Kali-linux
  menuentry "kali-linux-1.1.0a-amd64" {
    set isofile="/boot/bootiso/kali-linux-xfce-2018.4-amd64.iso"
    loopback loop (hd0,5)$isofile
    linux (loop)/live/vmlinuz boot=live findiso=$isofile noconfig=sudo username=root hostname=kali
    initrd (loop)/live/initrd.img
  }
